version: '3'

services:

  api:
    build:
      context: .
    env_file:
      - .env
    container_name: api
    restart: on-failure
    expose:
      - 8000
    ports:
      - 8000:8000
    command: [ "/docker/api.sh" ]
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    expose:
      - 27017
    ports:
      - '27017:27017'

volumes:
  mongo: